name: Basic CI Check

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: List files
      run: ls -la
      
    - name: Basic check
      run: echo "Repository check completed successfully"
