name: Python Application CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # No hay dependencias externas para instalar
    
    - name: Create test directories
      run: |
        mkdir -p clientes
    
    - name: Verify files exist
      run: |
        # Asegurarse de que el archivo principal existe
        if [ ! -f sky_client_system.py ]; then
          echo "ERROR: El archivo sky_client_system.py no existe"
          exit 1
        else
          echo "Verificación de archivos completada con éxito"
        fi
