name: Python Application CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create test directories
      run: |
        mkdir -p clientes
    
    - name: Run tests
      run: |
        # Ejecuta pruebas simples para verificar que el sistema funcione
        python -c "import os; assert os.path.exists('sky_client_system.py'), 'El archivo principal no existe'"
    
    - name: Save work directory
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: app-files
        path: |
          sky_client_system.py
          clientes/
          
  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-files
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Display structure of downloaded files
      run: ls -R
